name: Create CloudFormation Stack

on:
  workflow_dispatch:
  pull_request:

jobs:
  create_stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change this to your desired AWS region

      - name: Create CloudFormation Stack
        run: |
          aws cloudformation deploy --stack-name myteststackbeta --template-file ec2.yaml

      - name: Get Public IP from CloudFormation Stack
        id: get_ip
        run: |
          IP=$(aws cloudformation describe-stacks \
            --stack-name myteststack \
            --query "Stacks[0].Outputs[?OutputKey=='InstancePublicIp'].OutputValue" \
            --output text)
          echo "PUBLIC_IP=$IP" >> $GITHUB_ENV

      - name: Run Smoke Test
        run: |
          echo "Testing http://$PUBLIC_IP"
          curl --fail --connect-timeout 10 --max-time 20 http://$PUBLIC_IP || exit 1
